version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: imagenetwork
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:

volumes:
  postgres: