version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: imagenetwork
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

  api:
    container_name: imagenetwork-backend-api
    image: imagenetwork-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/imagenetwork?stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      - postgres
    profiles:
      - prod-test

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:

volumes:
  postgres: