spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/imagenetwork"
    username: postgres
    password: test
#  properties:
#    javax:
#      persistence:
#        schema-generation:
#          scripts:
#            action: create
#            create-target: test.sql
#            create-source: metadata